// styles/fishingLicenseScreenStyles.ts
import { StyleSheet, Platform } from "react-native";
import { colors, spacing, typography, borderRadius, shadows, modals } from "./common";
import { Theme } from './theme';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
    borderTopLeftRadius: borderRadius.md,
    borderTopRightRadius: borderRadius.md,
  },
  contentContainer: {
    flexGrow: 1,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  headerActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    padding: spacing.md,
  },
  infoButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  cardContainer: {
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.lg,
  },
  licenseCard: {
    borderRadius: borderRadius.lg,
    overflow: "hidden",
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  licenseCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.2)",
  },
  licenseLogoContainer: {
    width: 50,
    height: 50,
    backgroundColor: colors.white,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    marginRight: spacing.md,
    overflow: "hidden",
  },
  licenseLogo: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  licenseHeaderText: {
    flex: 1,
  },
  licenseInfoButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: spacing.sm,
  },
  licenseState: {
    ...typography.h4,
    color: colors.white,
    opacity: 0.9,
  },
  licenseTitle: {
    ...typography.h2,
    color: colors.white,
    fontWeight: "bold",
  },
  licenseContent: {
    padding: spacing.md,
  },
  licenseSection: {
    marginBottom: spacing.md,
    padding: spacing.md,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: borderRadius.md,
  },
  licenseSectionTitle: {
    ...typography.h3,
    color: colors.white,
    marginBottom: spacing.sm,
  },
  licenseRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.xs,
  },
  licenseLabel: {
    ...typography.bodySmall,
    color: colors.white,
    opacity: 0.8,
    width: 90,
  },
  licenseValue: {
    ...typography.body,
    color: colors.white,
    flex: 1,
  },
  licenseFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: spacing.md,
  },
  licenseFooterText: {
    ...typography.caption,
    color: colors.white,
    opacity: 0.7,
    flex: 1,
    marginRight: spacing.sm,
  },
  licenseEditButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  actionsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.lg,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.md,
    flex: 1,
    marginHorizontal: spacing.xs,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  actionButtonText: {
    ...typography.button,
    color: colors.white,
    marginLeft: spacing.xs,
  },
  secondaryButton: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  secondaryButtonText: {
    ...typography.button,
    color: colors.primary,
    marginLeft: spacing.xs,
  },
  outlineButton: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: colors.primary,
    marginTop: spacing.lg,
  },
  outlineButtonText: {
    ...typography.button,
    color: colors.primary,
  },
  infoContainer: {
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.lg,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  infoTitle: {
    ...typography.h2,
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  infoSubtitle: {
    ...typography.h3,
    color: colors.textPrimary,
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },
  infoText: {
    ...typography.body,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
  },
  bulletList: {
    marginVertical: spacing.sm,
  },
  bulletItem: {
    flexDirection: "row",
    marginBottom: spacing.xs,
    alignItems: "flex-start",
  },
  bullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
    marginTop: 7,
    marginRight: spacing.sm,
  },
  bulletText: {
    ...typography.body,
    color: colors.textSecondary,
    flex: 1,
  },
  emptyStateContainer: {
    alignItems: "center",
    paddingTop: spacing.xxl,
  },
  emptyStateImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: spacing.lg,
    opacity: 0.8,
  },
  emptyStateTitle: {
    ...typography.h1,
    color: colors.textPrimary,
    marginBottom: spacing.sm,
    textAlign: "center",
  },
  emptyStateText: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: "center",
    marginBottom: spacing.xl,
    paddingHorizontal: spacing.xl,
  },
  emptyStateInfoContainer: {
    width: "100%",
    paddingHorizontal: spacing.lg,
    marginTop: spacing.xl,
  },
  // Form header - matching ProfileScreen pattern
  formHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: 60,
    paddingBottom: spacing.xl,
    backgroundColor: colors.primaryDark,
    borderBottomLeftRadius: borderRadius.md,
    borderBottomRightRadius: borderRadius.md,
  },
  formCloseButton: {
    width: 40,
    height: 40,
    borderRadius: borderRadius.md,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  formHeaderTitle: {
    ...typography.h1,
    color: colors.white,
    fontSize: 20,
  },
  formContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  formContentContainer: {
    padding: spacing.lg,
  },
  formSection: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  formSectionTitle: {
    ...typography.heading,
    color: colors.primary,
    marginBottom: spacing.md,
  },
  inputGroup: {
    marginBottom: spacing.md,
  },
  inputLabel: {
    ...typography.bodySmall,
    fontWeight: '600',
    color: colors.darkGray,
    marginBottom: spacing.sm,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: Platform.OS === 'ios' ? spacing.sm : spacing.sm,
    fontSize: 16,
    color: colors.black,
    backgroundColor: colors.white,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputText: {
    fontSize: 16,
    color: colors.textPrimary,
    flex: 1,
  },
  inputPlaceholder: {
    fontSize: 16,
    color: colors.textTertiary,
    flex: 1,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: "top",
    paddingTop: spacing.sm,
  },
  dateInputRow: {
    flexDirection: "row",
  },
  formButtonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: spacing.lg,
  },
  formButton: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.md,
    alignItems: "center",
    justifyContent: "center",
  },
  formSaveButton: {
    backgroundColor: colors.primary,
    marginLeft: spacing.sm,
  },
  formSaveButtonText: {
    ...typography.button,
    color: colors.white,
  },
  formCancelButton: {
    backgroundColor: colors.white,
    marginRight: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  formCancelButtonText: {
    ...typography.button,
    color: colors.darkGray,
  },
  // Date picker - matching ProfileScreen pattern
  datePickerContainer: {
    backgroundColor: colors.white,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 10,
  },
  datePickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  datePickerTitle: {
    ...typography.subtitle,
    color: colors.textPrimary,
  },
  datePickerCancel: {
    ...typography.bodySmall,
    color: colors.darkGray,
  },
  datePickerDone: {
    ...typography.bodySmall,
    color: colors.primary,
    fontWeight: '600',
  },
  datePicker: {
    backgroundColor: colors.white,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    width: "90%",
    maxHeight: "80%",
    overflow: 'hidden',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  modalTitle: {
    ...typography.h2,
    color: colors.textPrimary,
    marginBottom: spacing.md,
  },
  modalText: {
    ...typography.body,
    color: colors.textSecondary,
    marginBottom: spacing.md,
  },
  modalSectionTitle: {
    ...typography.h3,
    color: colors.textPrimary,
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },
  modalBulletList: {
    marginBottom: spacing.lg,
  },
  modalBulletItem: {
    flexDirection: "row",
    marginBottom: spacing.xs,
    alignItems: "flex-start",
  },
  modalBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
    marginTop: 7,
    marginRight: spacing.sm,
  },
  modalBulletText: {
    ...typography.body,
    color: colors.textSecondary,
    flex: 1,
  },
  modalButton: {
    backgroundColor: colors.lightGray,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    alignItems: "center",
    marginTop: spacing.md,
  },
  modalButtonText: {
    ...typography.button,
    color: colors.textSecondary,
  },
  modalLookupButton: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  modalLookupButtonText: {
    ...typography.button,
    color: colors.white,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  licenseTypeModalContent: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    width: "90%",
    padding: spacing.lg,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  licenseTypeItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightestGray,
    marginVertical: 2,
  },
  licenseTypeItemSelected: {
    backgroundColor: colors.lightestGray,
  },
  licenseTypeText: {
    ...typography.body,
    color: colors.textPrimary,
    flex: 1,
  },
  // ─── Zero-state empty license card ────────────────────────────────────────
  emptyLicenseCard: {
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    marginHorizontal: spacing.lg,
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
    backgroundColor: '#EEF2F4',
    borderWidth: 1.5,
    borderColor: '#CFD8DC',
    borderStyle: 'dashed',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  emptyCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  emptyFlagWrapper: {
    position: 'relative',
  },
  emptyFlagOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(180, 195, 200, 0.5)',
    borderRadius: 4,
  },
  emptyCardTitleBlock: {
    flex: 1,
    justifyContent: 'center',
  },
  emptyCardTitleLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    color: colors.mediumGray,
  },
  emptyCardTitleMain: {
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.4,
    color: colors.mediumGray,
    marginTop: 1,
  },
  emptyPlaceholders: {
    marginTop: spacing.lg,
    marginBottom: spacing.md,
  },
  placeholderLine: {
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.textTertiary,
  },
  emptyCardFooter: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginTop: spacing.lg,
  },
  emptyCardFieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    color: colors.mediumGray,
    marginBottom: 4,
  },
  addLicensePill: {
    backgroundColor: colors.primary,
    borderRadius: 24,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  addLicensePillText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.3,
  },

  // ─── Section header label (uppercase eyebrow) ──────────────────────────────
  infoSectionHeader: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    color: colors.mediumGray,
    textTransform: 'uppercase',
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },

  // ─── Form label row (label + info icon) ───────────────────────────────────
  inputLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: spacing.sm,
  },

  // ─── Expandable section content ────────────────────────────────────────────
  expandableBulletList: {
    gap: spacing.sm,
    paddingTop: spacing.sm,
  },
  expandableBulletRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    alignItems: 'flex-start',
  },
  expandableBullet: {
    fontSize: 14,
    color: colors.primary,
    lineHeight: 20,
  },
  expandableBulletText: {
    flex: 1,
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  expandableLinkText: {
    color: colors.primary,
    textDecorationLine: 'underline',
  },
  lookupButton: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    paddingVertical: 12,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  lookupButtonText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '600',
  },

  // ─── FAQ items ─────────────────────────────────────────────────────────────
  faqItem: {
    paddingVertical: spacing.sm,
  },
  faqItemBorder: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.06)',
  },
  faqQuestion: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  faqAnswer: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 19,
  },

  // ─── External link row ─────────────────────────────────────────────────────
  externalLinkRow: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.sm,
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  externalLinkText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.primary,
  },

  // Date picker modal styles - uses common modal styles
  dateModalOverlay: modals.overlay,
  dateModalContent: {
    ...modals.content,
    padding: spacing.lg,
  },
  dateModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  dateModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  datePickerInline: {
    height: 350,
    width: '100%',
    backgroundColor: colors.white,
  },
  dateModalConfirmButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 16,
  },
  dateModalConfirmText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
});

export default styles;

// Theme-aware factory function
export const createFishingLicenseScreenStyles = (theme: Theme) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
      borderTopLeftRadius: borderRadius.md,
      borderTopRightRadius: borderRadius.md,
    },
    contentContainer: {
      flexGrow: 1,
      paddingTop: spacing.lg,
      paddingBottom: spacing.xxl,
    },
    headerActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      padding: spacing.md,
    },
    infoButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 3,
    },
    cardContainer: {
      paddingHorizontal: spacing.lg,
      marginBottom: spacing.lg,
    },
    licenseCard: {
      borderRadius: borderRadius.lg,
      overflow: "hidden",
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
      elevation: 5,
    },
    licenseCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: "rgba(255, 255, 255, 0.2)",
    },
    licenseLogoContainer: {
      width: 50,
      height: 50,
      backgroundColor: theme.colors.white,
      borderRadius: 25,
      alignItems: "center",
      justifyContent: "center",
      marginRight: spacing.md,
      overflow: "hidden",
    },
    licenseLogo: {
      width: 44,
      height: 44,
      borderRadius: 22,
    },
    licenseHeaderText: {
      flex: 1,
    },
    licenseInfoButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: "rgba(255, 255, 255, 0.2)",
      alignItems: "center",
      justifyContent: "center",
      marginLeft: spacing.sm,
    },
    licenseState: {
      ...typography.h4,
      color: theme.colors.white,
      opacity: 0.9,
    },
    licenseTitle: {
      ...typography.h2,
      color: theme.colors.white,
      fontWeight: "bold",
    },
    licenseContent: {
      padding: spacing.md,
    },
    licenseSection: {
      marginBottom: spacing.md,
      padding: spacing.md,
      backgroundColor: "rgba(255, 255, 255, 0.15)",
      borderRadius: borderRadius.md,
    },
    licenseSectionTitle: {
      ...typography.h3,
      color: theme.colors.white,
      marginBottom: spacing.sm,
    },
    licenseRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: spacing.xs,
    },
    licenseLabel: {
      ...typography.bodySmall,
      color: theme.colors.white,
      opacity: 0.8,
      width: 90,
    },
    licenseValue: {
      ...typography.body,
      color: theme.colors.white,
      flex: 1,
    },
    licenseFooter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: spacing.md,
    },
    licenseFooterText: {
      ...typography.caption,
      color: theme.colors.white,
      opacity: 0.7,
      flex: 1,
      marginRight: spacing.sm,
    },
    licenseEditButton: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: "rgba(255, 255, 255, 0.2)",
      alignItems: "center",
      justifyContent: "center",
    },
    actionsContainer: {
      flexDirection: "row",
      justifyContent: "center",
      paddingHorizontal: spacing.lg,
      marginBottom: spacing.lg,
    },
    actionButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.primary,
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.lg,
      borderRadius: borderRadius.md,
      flex: 1,
      marginHorizontal: spacing.xs,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    actionButtonText: {
      ...typography.button,
      color: theme.colors.white,
      marginLeft: spacing.xs,
    },
    secondaryButton: {
      backgroundColor: theme.colors.white,
      borderWidth: 1,
      borderColor: theme.colors.primary,
    },
    secondaryButtonText: {
      ...typography.button,
      color: theme.colors.primary,
      marginLeft: spacing.xs,
    },
    outlineButton: {
      backgroundColor: "transparent",
      borderWidth: 1,
      borderColor: theme.colors.primary,
      marginTop: spacing.lg,
    },
    outlineButtonText: {
      ...typography.button,
      color: theme.colors.primary,
    },
    infoContainer: {
      paddingHorizontal: spacing.lg,
      backgroundColor: theme.colors.white,
      borderRadius: borderRadius.lg,
      padding: spacing.lg,
      marginHorizontal: spacing.lg,
      marginBottom: spacing.lg,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    infoTitle: {
      ...typography.h2,
      color: theme.colors.textPrimary,
      marginBottom: spacing.sm,
    },
    infoSubtitle: {
      ...typography.h3,
      color: theme.colors.textPrimary,
      marginTop: spacing.md,
      marginBottom: spacing.sm,
    },
    infoText: {
      ...typography.body,
      color: theme.colors.textSecondary,
      marginBottom: spacing.sm,
    },
    bulletList: {
      marginVertical: spacing.sm,
    },
    bulletItem: {
      flexDirection: "row",
      marginBottom: spacing.xs,
      alignItems: "flex-start",
    },
    bullet: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.colors.primary,
      marginTop: 7,
      marginRight: spacing.sm,
    },
    bulletText: {
      ...typography.body,
      color: theme.colors.textSecondary,
      flex: 1,
    },
    emptyStateContainer: {
      alignItems: "center",
      paddingTop: spacing.xxl,
    },
    emptyStateImage: {
      width: 120,
      height: 120,
      borderRadius: 60,
      marginBottom: spacing.lg,
      opacity: 0.8,
    },
    emptyStateTitle: {
      ...typography.h1,
      color: theme.colors.textPrimary,
      marginBottom: spacing.sm,
      textAlign: "center",
    },
    emptyStateText: {
      ...typography.body,
      color: theme.colors.textSecondary,
      textAlign: "center",
      marginBottom: spacing.xl,
      paddingHorizontal: spacing.xl,
    },
    emptyStateInfoContainer: {
      width: "100%",
      paddingHorizontal: spacing.lg,
      marginTop: spacing.xl,
    },
    formHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.lg,
      paddingTop: 60,
      paddingBottom: spacing.xl,
      backgroundColor: theme.colors.primaryDark,
      borderBottomLeftRadius: borderRadius.md,
      borderBottomRightRadius: borderRadius.md,
    },
    formCloseButton: {
      width: 40,
      height: 40,
      borderRadius: borderRadius.md,
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    formHeaderTitle: {
      ...typography.h1,
      color: theme.colors.textOnPrimary,
      fontSize: 20,
    },
    formContainer: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    formContentContainer: {
      padding: spacing.lg,
    },
    formSection: {
      backgroundColor: theme.colors.white,
      borderRadius: borderRadius.lg,
      padding: spacing.lg,
      marginBottom: spacing.lg,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    formSectionTitle: {
      ...typography.heading,
      color: theme.colors.primary,
      marginBottom: spacing.md,
    },
    inputGroup: {
      marginBottom: spacing.md,
    },
    inputLabel: {
      ...typography.bodySmall,
      fontWeight: '600',
      color: theme.colors.darkGray,
      marginBottom: spacing.sm,
    },
    input: {
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: borderRadius.md,
      paddingHorizontal: spacing.sm,
      paddingVertical: Platform.OS === 'ios' ? spacing.sm : spacing.sm,
      fontSize: 16,
      color: theme.colors.black,
      backgroundColor: theme.colors.white,
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    inputText: {
      fontSize: 16,
      color: theme.colors.textPrimary,
      flex: 1,
    },
    inputPlaceholder: {
      fontSize: 16,
      color: theme.colors.textTertiary,
      flex: 1,
    },
    textArea: {
      minHeight: 80,
      textAlignVertical: "top",
      paddingTop: spacing.sm,
    },
    dateInputRow: {
      flexDirection: "row",
    },
    formButtonRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: spacing.lg,
    },
    formButton: {
      flex: 1,
      paddingVertical: spacing.sm,
      borderRadius: borderRadius.md,
      alignItems: "center",
      justifyContent: "center",
    },
    formSaveButton: {
      backgroundColor: theme.colors.primary,
      marginLeft: spacing.sm,
    },
    formSaveButtonText: {
      ...typography.button,
      color: theme.colors.white,
    },
    formCancelButton: {
      backgroundColor: theme.colors.white,
      marginRight: spacing.sm,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    formCancelButtonText: {
      ...typography.button,
      color: theme.colors.darkGray,
    },
    datePickerContainer: {
      backgroundColor: theme.colors.white,
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
      elevation: 10,
    },
    datePickerHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    datePickerTitle: {
      ...typography.subtitle,
      color: theme.colors.textPrimary,
    },
    datePickerCancel: {
      ...typography.bodySmall,
      color: theme.colors.darkGray,
    },
    datePickerDone: {
      ...typography.bodySmall,
      color: theme.colors.primary,
      fontWeight: '600',
    },
    datePicker: {
      backgroundColor: theme.colors.white,
    },
    modalContainer: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      backgroundColor: theme.colors.white,
      borderRadius: borderRadius.lg,
      width: "90%",
      maxHeight: "80%",
      overflow: 'hidden',
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 5,
    },
    modalTitle: {
      ...typography.h2,
      color: theme.colors.textPrimary,
      marginBottom: spacing.md,
    },
    modalText: {
      ...typography.body,
      color: theme.colors.textSecondary,
      marginBottom: spacing.md,
    },
    modalSectionTitle: {
      ...typography.h3,
      color: theme.colors.textPrimary,
      marginTop: spacing.md,
      marginBottom: spacing.sm,
    },
    modalBulletList: {
      marginBottom: spacing.lg,
    },
    modalBulletItem: {
      flexDirection: "row",
      marginBottom: spacing.xs,
      alignItems: "flex-start",
    },
    modalBullet: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.colors.primary,
      marginTop: 7,
      marginRight: spacing.sm,
    },
    modalBulletText: {
      ...typography.body,
      color: theme.colors.textSecondary,
      flex: 1,
    },
    modalButton: {
      backgroundColor: theme.colors.lightGray,
      borderRadius: borderRadius.md,
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.lg,
      alignItems: "center",
      marginTop: spacing.md,
    },
    modalButtonText: {
      ...typography.button,
      color: theme.colors.textSecondary,
    },
    modalLookupButton: {
      backgroundColor: theme.colors.primary,
      borderRadius: borderRadius.md,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.lg,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      marginTop: spacing.sm,
      marginBottom: spacing.sm,
    },
    modalLookupButtonText: {
      ...typography.button,
      color: theme.colors.white,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    licenseTypeModalContent: {
      backgroundColor: theme.colors.white,
      borderRadius: borderRadius.lg,
      width: "90%",
      padding: spacing.lg,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 5,
    },
    licenseTypeItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.lightestGray,
      marginVertical: 2,
    },
    licenseTypeItemSelected: {
      backgroundColor: theme.colors.lightestGray,
    },
    licenseTypeText: {
      ...typography.body,
      color: theme.colors.textPrimary,
      flex: 1,
    },
    emptyLicenseCard: {
      borderRadius: borderRadius.lg,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.xl,
      marginHorizontal: spacing.lg,
      marginTop: spacing.sm,
      marginBottom: spacing.sm,
      // Dark mode: use the surface navy so the card doesn't blaze against
      // the deep ocean background. Light mode keeps the cool gray-blue.
      backgroundColor: theme.isDark ? theme.colors.surface : '#EEF2F4',
      borderWidth: 1.5,
      borderColor: theme.isDark ? theme.colors.border : '#CFD8DC',
      borderStyle: 'dashed',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 2,
    },
    emptyCardHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: spacing.sm,
    },
    emptyFlagWrapper: {
      position: 'relative',
    },
    emptyFlagOverlay: {
      ...StyleSheet.absoluteFillObject,
      // Light mode: cool gray-blue wash. Dark mode: dark tint to mute the flag.
      backgroundColor: theme.isDark ? 'rgba(0, 0, 0, 0.45)' : 'rgba(180, 195, 200, 0.5)',
      borderRadius: 4,
    },
    emptyCardTitleBlock: {
      flex: 1,
      justifyContent: 'center',
    },
    emptyCardTitleLabel: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      color: theme.colors.mediumGray,
    },
    emptyCardTitleMain: {
      fontSize: 14,
      fontWeight: '800',
      letterSpacing: 0.4,
      color: theme.colors.mediumGray,
      marginTop: 1,
    },
    emptyPlaceholders: {
      marginTop: spacing.lg,
      marginBottom: spacing.md,
    },
    placeholderLine: {
      height: 10,
      borderRadius: 5,
      backgroundColor: theme.colors.textTertiary,
    },
    emptyCardFooter: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      marginTop: spacing.lg,
    },
    emptyCardFieldLabel: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      color: theme.colors.mediumGray,
      marginBottom: 4,
    },
    addLicensePill: {
      backgroundColor: theme.colors.primary,
      borderRadius: 24,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    addLicensePillText: {
      color: theme.colors.white,
      fontSize: 15,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
    infoSectionHeader: {
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.8,
      color: theme.colors.mediumGray,
      textTransform: 'uppercase',
      marginHorizontal: spacing.lg,
      marginTop: spacing.lg,
      marginBottom: spacing.sm,
    },
    inputLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: spacing.sm,
    },
    expandableBulletList: {
      gap: spacing.sm,
      paddingTop: spacing.sm,
    },
    expandableBulletRow: {
      flexDirection: 'row',
      gap: spacing.sm,
      alignItems: 'flex-start',
    },
    expandableBullet: {
      fontSize: 14,
      color: theme.colors.primary,
      lineHeight: 20,
    },
    expandableBulletText: {
      flex: 1,
      fontSize: 14,
      color: theme.colors.textSecondary,
      lineHeight: 20,
    },
    expandableLinkText: {
      color: theme.colors.primary,
      textDecorationLine: 'underline',
    },
    lookupButton: {
      backgroundColor: theme.colors.primary,
      borderRadius: borderRadius.md,
      paddingVertical: 12,
      paddingHorizontal: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    lookupButtonText: {
      color: theme.colors.white,
      fontSize: 15,
      fontWeight: '600',
    },
    faqItem: {
      paddingVertical: spacing.sm,
    },
    faqItemBorder: {
      borderTopWidth: 1,
      borderTopColor: 'rgba(0,0,0,0.06)',
    },
    faqQuestion: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      marginBottom: 4,
    },
    faqAnswer: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      lineHeight: 19,
    },
    externalLinkRow: {
      marginHorizontal: spacing.lg,
      marginTop: spacing.sm,
      backgroundColor: theme.colors.white,
      borderRadius: borderRadius.lg,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },
    externalLinkText: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.colors.primary,
    },
    dateModalOverlay: modals.overlay,
    dateModalContent: {
      ...modals.content,
      padding: spacing.lg,
    },
    dateModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: spacing.md,
    },
    dateModalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    datePickerInline: {
      height: 350,
      width: '100%',
      backgroundColor: theme.colors.white,
    },
    dateModalConfirmButton: {
      backgroundColor: theme.colors.primary,
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: 'center',
      marginTop: 16,
    },
    dateModalConfirmText: {
      color: theme.colors.white,
      fontSize: 16,
      fontWeight: '600',
    },
  });