// styles/fishingLicenseScreenStyles.ts
import { StyleSheet, Platform } from "react-native";
import { colors, spacing, typography, borderRadius } from "./common";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
    borderTopLeftRadius: borderRadius.md,
    borderTopRightRadius: borderRadius.md,
  },
  contentContainer: {
    flexGrow: 1,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  headerActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    padding: spacing.md,
  },
  infoButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  cardContainer: {
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.lg,
  },
  licenseCard: {
    borderRadius: borderRadius.lg,
    overflow: "hidden",
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  licenseCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.2)",
  },
  licenseLogoContainer: {
    width: 50,
    height: 50,
    backgroundColor: colors.white,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    marginRight: spacing.md,
    overflow: "hidden",
  },
  licenseLogo: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  licenseHeaderText: {
    flex: 1,
  },
  licenseInfoButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: spacing.sm,
  },
  licenseState: {
    ...typography.h4,
    color: colors.white,
    opacity: 0.9,
  },
  licenseTitle: {
    ...typography.h2,
    color: colors.white,
    fontWeight: "bold",
  },
  licenseContent: {
    padding: spacing.md,
  },
  licenseSection: {
    marginBottom: spacing.md,
    padding: spacing.md,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: borderRadius.md,
  },
  licenseSectionTitle: {
    ...typography.h3,
    color: colors.white,
    marginBottom: spacing.sm,
  },
  licenseRow: {
    flexDirection: "row",
    marginBottom: spacing.xs,
  },
  licenseLabel: {
    ...typography.bodySmall,
    color: colors.white,
    opacity: 0.8,
    width: 90,
  },
  licenseValue: {
    ...typography.body,
    color: colors.white,
    flex: 1,
  },
  licenseFooter: {
    alignItems: "center",
    marginTop: spacing.md,
  },
  licenseFooterText: {
    ...typography.caption,
    color: colors.white,
    opacity: 0.7,
  },
  actionsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.lg,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.md,
    flex: 1,
    marginHorizontal: spacing.xs,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  actionButtonText: {
    ...typography.button,
    color: colors.white,
    marginLeft: spacing.xs,
  },
  secondaryButton: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  secondaryButtonText: {
    ...typography.button,
    color: colors.primary,
    marginLeft: spacing.xs,
  },
  outlineButton: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: colors.primary,
    marginTop: spacing.lg,
  },
  outlineButtonText: {
    ...typography.button,
    color: colors.primary,
  },
  infoContainer: {
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.lg,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  infoTitle: {
    ...typography.h2,
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  infoSubtitle: {
    ...typography.h3,
    color: colors.textPrimary,
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },
  infoText: {
    ...typography.body,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
  },
  bulletList: {
    marginVertical: spacing.sm,
  },
  bulletItem: {
    flexDirection: "row",
    marginBottom: spacing.xs,
    alignItems: "flex-start",
  },
  bullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
    marginTop: 7,
    marginRight: spacing.sm,
  },
  bulletText: {
    ...typography.body,
    color: colors.textSecondary,
    flex: 1,
  },
  emptyStateContainer: {
    alignItems: "center",
    paddingTop: spacing.xxl,
  },
  emptyStateImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: spacing.lg,
    opacity: 0.8,
  },
  emptyStateTitle: {
    ...typography.h1,
    color: colors.textPrimary,
    marginBottom: spacing.sm,
    textAlign: "center",
  },
  emptyStateText: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: "center",
    marginBottom: spacing.xl,
    paddingHorizontal: spacing.xl,
  },
  emptyStateInfoContainer: {
    width: "100%",
    paddingHorizontal: spacing.lg,
    marginTop: spacing.xl,
  },
  // Form header - matching ProfileScreen pattern
  formHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: 60,
    paddingBottom: spacing.xl,
    backgroundColor: colors.primary,
    borderBottomLeftRadius: borderRadius.md,
    borderBottomRightRadius: borderRadius.md,
  },
  formCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  formHeaderTitle: {
    ...typography.h1,
    color: colors.white,
    fontSize: 20,
  },
  formContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  formContentContainer: {
    padding: spacing.lg,
  },
  formSection: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  formSectionTitle: {
    ...typography.heading,
    color: colors.primary,
    marginBottom: spacing.md,
  },
  inputGroup: {
    marginBottom: spacing.md,
  },
  inputLabel: {
    ...typography.bodySmall,
    fontWeight: '600',
    color: colors.darkGray,
    marginBottom: spacing.sm,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: Platform.OS === 'ios' ? spacing.sm : spacing.sm,
    fontSize: 16,
    color: colors.black,
    backgroundColor: colors.white,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputText: {
    fontSize: 16,
    color: colors.textPrimary,
    flex: 1,
  },
  inputPlaceholder: {
    fontSize: 16,
    color: colors.textTertiary,
    flex: 1,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: "top",
    paddingTop: spacing.sm,
  },
  dateInputRow: {
    flexDirection: "row",
  },
  formButtonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: spacing.lg,
  },
  formButton: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.md,
    alignItems: "center",
    justifyContent: "center",
  },
  formSaveButton: {
    backgroundColor: colors.primary,
    marginLeft: spacing.sm,
  },
  formSaveButtonText: {
    ...typography.button,
    color: colors.white,
  },
  formCancelButton: {
    backgroundColor: colors.white,
    marginRight: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  formCancelButtonText: {
    ...typography.button,
    color: colors.darkGray,
  },
  // Date picker - matching ProfileScreen pattern
  datePickerContainer: {
    backgroundColor: colors.white,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 10,
  },
  datePickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  datePickerTitle: {
    ...typography.subtitle,
    color: colors.textPrimary,
  },
  datePickerCancel: {
    ...typography.bodySmall,
    color: colors.darkGray,
  },
  datePickerDone: {
    ...typography.bodySmall,
    color: colors.primary,
    fontWeight: '600',
  },
  datePicker: {
    backgroundColor: colors.white,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    width: "90%",
    maxHeight: "80%",
    padding: spacing.lg,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  modalTitle: {
    ...typography.h2,
    color: colors.textPrimary,
    marginBottom: spacing.md,
  },
  modalText: {
    ...typography.body,
    color: colors.textSecondary,
    marginBottom: spacing.md,
  },
  modalSectionTitle: {
    ...typography.h3,
    color: colors.textPrimary,
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },
  modalBulletList: {
    marginBottom: spacing.lg,
  },
  modalBulletItem: {
    flexDirection: "row",
    marginBottom: spacing.xs,
    alignItems: "flex-start",
  },
  modalBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
    marginTop: 7,
    marginRight: spacing.sm,
  },
  modalBulletText: {
    ...typography.body,
    color: colors.textSecondary,
    flex: 1,
  },
  modalButton: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    alignItems: "center",
    marginTop: spacing.md,
  },
  modalButtonText: {
    ...typography.button,
    color: colors.white,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  licenseTypeModalContent: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    width: "90%",
    padding: spacing.lg,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  licenseTypeItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightestGray,
    marginVertical: 2,
  },
  licenseTypeItemSelected: {
    backgroundColor: colors.lightestGray,
  },
  licenseTypeText: {
    ...typography.body,
    color: colors.textPrimary,
    flex: 1,
  },
  // Date picker modal styles - matching ReportFormScreen and ProfileScreen
  dateModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateModalContent: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 20,
    width: '90%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 10,
  },
  dateModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  dateModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  datePickerInline: {
    height: 350,
    width: '100%',
  },
  dateModalConfirmButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 16,
  },
  dateModalConfirmText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
});

export default styles;