import { StyleSheet, Platform, Dimensions } from 'react-native';
import { colors, spacing, borderRadius, shadows, typography, modals } from './common';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollView: {
    flex: 1,
    backgroundColor: colors.background,
  },
  contentContainer: {
    flexGrow: 1,
  },
  // Invisible spacer that shows primary color when pulling down at top
  topBounceArea: {
    backgroundColor: colors.primary,
    height: 500,
    marginTop: -500,
  },
  // Content area with light background
  contentArea: {
    backgroundColor: colors.background,
    flexGrow: 1,
    paddingTop: spacing.md,
    paddingBottom: spacing.xl * 2,
  },
  // Header row containing back button and title
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: spacing.lg,
  },
  // Back Button inside header
  backButton: {
    width: 40,
    height: 40,
    borderRadius: borderRadius.md,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Spacer to balance the back button on the right
  headerSpacer: {
    width: 40,
    height: 40,
  },
  // Profile Header
  profileHeader: {
    backgroundColor: colors.primary,
    paddingTop: 60,
    paddingBottom: spacing.xl,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
  },
  headerTitle: {
    ...typography.h1,
    color: colors.white,
    fontSize: 20,
    textAlign: 'center',
    flex: 1,
  },
  profileImageContainer: {
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(255,255,255,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.sm,
    marginBottom: spacing.xl,
    overflow: 'visible',
    position: 'relative',
    borderWidth: 1,
    borderColor: colors.border,
  },
  profileImage: {
    width: 160,
    height: 160,
    borderRadius: 80,
  },
  cameraIconContainer: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
    ...shadows.small,
  },
  profileName: {
    ...typography.h1,
    color: colors.white,
    marginBottom: spacing.xxs,
  },
  profileSubtitle: {
    ...typography.body,
    color: colors.white,
    opacity: 0.9,
  },
  // Info Section
  infoContainer: {
    backgroundColor: colors.white,
    marginHorizontal: spacing.lg,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginTop: -spacing.xl,
    ...shadows.medium,
  },
  infoSection: {
    marginBottom: spacing.lg,
  },
  infoSectionTitle: {
    ...typography.heading,
    color: colors.primary,
    marginBottom: spacing.md,
  },
  infoItem: {
    flexDirection: 'row',
    marginBottom: spacing.md,
  },
  infoIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  infoContent: {
    flex: 1,
    justifyContent: 'center',
  },
  infoLabel: {
    ...typography.bodySmall,
    color: colors.darkGray,
    marginBottom: spacing.xxs,
  },
  infoValue: {
    ...typography.body,
    color: colors.black,
  },
  editButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.small,
  },
  editButtonText: {
    ...typography.button,
    color: colors.white,
    marginLeft: spacing.xs,
  },
  // License Section
  licenseSection: {
    backgroundColor: colors.white,
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    ...shadows.medium,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  sectionTitle: {
    ...typography.heading,
    color: colors.primary,
  },
  viewLicenseButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewLicenseText: {
    ...typography.bodySmall,
    color: colors.primary,
    fontWeight: '600',
    marginRight: spacing.xxs,
  },
  licenseDescription: {
    ...typography.body,
    color: colors.darkGray,
    marginTop: spacing.xs,
  },
  // Stats Section
  statsSection: {
    backgroundColor: colors.white,
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    ...shadows.medium,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.md,
  },
  statCard: {
    width: '30%',
    backgroundColor: colors.lightGray,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statValue: {
    ...typography.heading,
    color: colors.primary,
    marginBottom: spacing.xxs,
    textAlign: 'center',
  },
  statLabel: {
    ...typography.bodySmall,
    color: colors.darkGray,
    fontWeight: '600',
    textAlign: 'center',
  },
  // Form styles
  formContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  formContentContainer: {
    padding: spacing.lg,
  },
  formSection: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    ...shadows.small,
  },
  formSectionTitle: {
    ...typography.heading,
    color: colors.primary,
    marginBottom: spacing.md,
  },
  sectionDescription: {
    ...typography.body,
    color: colors.darkGray,
    marginBottom: spacing.md,
    marginTop: -spacing.xs,
  },
  toggleRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.md,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.white,
    alignItems: 'center',
  },
  toggleButtonActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  toggleButtonText: {
    ...typography.body,
    fontWeight: '600',
    color: colors.darkGray,
  },
  toggleButtonTextActive: {
    color: colors.primary,
  },
  helpText: {
    ...typography.bodySmall,
    color: colors.darkGray,
    marginTop: spacing.xxs,
    fontStyle: 'italic',
  },
  formHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: 60,
    paddingBottom: spacing.xl,
    backgroundColor: colors.primary,
    borderBottomLeftRadius: borderRadius.md,
    borderBottomRightRadius: borderRadius.md,
  },
  formCloseButton: {
    width: 40,
    height: 40,
    borderRadius: borderRadius.md,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  formHeaderTitle: {
    ...typography.h1,
    color: colors.white,
    fontSize: 20,
  },
  profilePhotoSection: {
    alignItems: 'center',
    marginTop: spacing.md,
    marginBottom: spacing.lg,
  },
  photoHelpText: {
    ...typography.bodySmall,
    color: colors.primary,
    marginTop: spacing.sm,
  },
  inputGroup: {
    marginBottom: spacing.md,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  nameInputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  nameInput: {
    flex: 1,
  },
  nameInputSpacer: {
    width: 12,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: spacing.xs,
  },
  inputLabel: {
    ...typography.bodySmall,
    fontWeight: '600',
    color: colors.darkGray,
    marginBottom: spacing.sm,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: Platform.OS === 'ios' ? spacing.sm : spacing.sm,
    fontSize: 16,
    color: colors.black,
    backgroundColor: colors.white,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputError: {
    borderColor: colors.error || '#FF3B30',
    borderWidth: 1,
  },
  errorText: {
    color: colors.error || '#FF3B30',
    fontSize: 12,
    marginTop: 4,
    marginLeft: 4,
  },
  // ZIP code input row layout
  zipInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  zipInput: {
    width: 100,
    flex: 0,
  },
  // ZIP code lookup feedback styles
  zipFeedback: {
    flex: 1,
    justifyContent: 'center',
    marginLeft: 4,
  },
  zipFeedbackLoading: {
    fontSize: 13,
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
  zipFeedbackSuccess: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  zipFeedbackSuccessText: {
    fontSize: 13,
    color: '#28a745',
    fontWeight: '500',
  },
  zipFeedbackWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  zipFeedbackWarningText: {
    fontSize: 13,
    color: '#ff9800',
    fontWeight: '500',
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
    paddingTop: spacing.sm,
  },
  inputText: {
    fontSize: 16,
    color: colors.black,
    flex: 1,
  },
  inputPlaceholder: {
    fontSize: 16,
    color: colors.textTertiary,
    flex: 1,
  },
  suggestionsContainer: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    marginTop: 4,
    height: 150,
    overflow: 'hidden',
    ...shadows.medium,
    zIndex: 999,
    position: 'absolute',
    top: 104, // Position below the text input (adjusted for your layout)
    left: 0,
    right: 0,
  },
  suggestionsScroll: {
    flex: 1,
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.white,
  },
  suggestionIcon: {
    marginRight: 8,
  },
  suggestionText: {
    fontSize: 14,
    color: colors.black,
    flex: 1,
  },
  formButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.xl,
  },
  formButton: {
    flex: 1,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formCancelButton: {
    backgroundColor: colors.white,
    marginRight: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  formSaveButton: {
    backgroundColor: colors.primary,
    marginLeft: spacing.sm,
  },
  formCancelButtonText: {
    ...typography.button,
    color: colors.darkGray,
  },
  formSaveButtonText: {
    ...typography.button,
    color: colors.white,
  },
  // Date picker modal styles - uses common modal styles
  dateModalOverlay: modals.overlay,
  dateModalContent: {
    ...modals.content,
    padding: spacing.lg,
  },
  dateModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  dateModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  datePickerContainer: {
    width: '100%',
    minHeight: 350,
    backgroundColor: colors.white,
    overflow: 'hidden',
  },
  datePickerInline: {
    height: 350,
    width: '100%',
    backgroundColor: colors.white,
  },
  dateModalConfirmButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 16,
  },
  dateModalConfirmText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
});

// Local styles for pending auth section
export const localStyles = StyleSheet.create({
  pendingAuthSection: {
    backgroundColor: '#FFF9E6',
    borderColor: '#FFD700',
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  pendingAuthHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  pendingAuthIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.sm,
  },
  pendingAuthTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  pendingAuthDesc: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: spacing.md,
    lineHeight: 20,
  },
  pendingAuthEmailContainer: {
    marginBottom: spacing.sm,
  },
  pendingAuthLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 4,
  },
  pendingAuthEmailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.white,
    borderRadius: borderRadius.sm,
    padding: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  pendingAuthEmail: {
    fontSize: 15,
    color: colors.textPrimary,
    flex: 1,
  },
  pendingAuthInput: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.sm,
    padding: spacing.sm,
    borderWidth: 1,
    borderColor: colors.primary,
    fontSize: 15,
    color: colors.textPrimary,
  },
  pendingAuthSentAt: {
    fontSize: 12,
    color: colors.textTertiary,
    marginBottom: spacing.md,
  },
  pendingAuthActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  pendingAuthButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.md,
    gap: 6,
  },
  pendingAuthResendButton: {
    backgroundColor: colors.primary,
    flex: 1,
  },
  pendingAuthCancelButton: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
  },
  pendingAuthButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  pendingAuthCancelText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '600',
  },
  // Rewards member section styles
  rewardsMemberSection: {
    backgroundColor: '#E8F5E9',
    borderColor: '#4CAF50',
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  rewardsMemberHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  rewardsMemberIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.sm,
  },
  rewardsMemberInfo: {
    flex: 1,
  },
  rewardsMemberTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  rewardsMemberEmail: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 2,
  },
  rewardsMemberDesc: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
    marginBottom: spacing.md,
  },
  signOutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 6,
  },
  signOutButtonText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '600',
  },
  // Sign in section styles
  signInSection: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.primary,
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  signInHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  signInIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.sm,
  },
  signInTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  signInDesc: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
    marginBottom: spacing.md,
  },
  signInForm: {
    marginTop: spacing.sm,
  },
  signInInputGroup: {
    marginBottom: spacing.sm,
  },
  signInLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 4,
  },
  signInInput: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.sm,
    padding: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    fontSize: 15,
    color: colors.textPrimary,
  },
  signInInputError: {
    borderColor: colors.error || '#FF3B30',
    borderWidth: 1,
  },
  signInInputErrorText: {
    color: colors.error || '#FF3B30',
    fontSize: 12,
    marginTop: 4,
  },
  signInNameRow: {
    flexDirection: 'row',
  },
  signInActions: {
    marginTop: spacing.sm,
    gap: spacing.sm,
  },
  signInSubmitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: colors.primary,
    gap: 8,
  },
  signInSubmitText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '600',
  },
  signInCancelButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
  },
  signInCancelText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '500',
  },
  joinRewardsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: colors.primary,
    gap: 8,
  },
  joinRewardsText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '600',
  },
  // Delete account section styles
  deleteAccountSection: {
    backgroundColor: '#FFF5F5',
    borderColor: '#FF3B30',
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginTop: spacing.lg,
    marginBottom: spacing.xl,
  },
  deleteAccountHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  deleteAccountIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FF3B30',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.sm,
  },
  deleteAccountTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FF3B30',
  },
  deleteAccountDesc: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
    marginBottom: spacing.md,
  },
  deleteAccountButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#FF3B30',
    gap: 6,
  },
  deleteAccountButtonText: {
    color: '#FF3B30',
    fontSize: 14,
    fontWeight: '600',
  },
  // Skeleton loader styles
  skeletonSection: {
    backgroundColor: colors.lightGray,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  skeletonHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  skeletonIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.border,
    marginRight: spacing.sm,
  },
  skeletonTextContainer: {
    flex: 1,
  },
  skeletonTitle: {
    width: 120,
    height: 16,
    borderRadius: 4,
    backgroundColor: colors.border,
    marginBottom: 6,
  },
  skeletonSubtitle: {
    width: 180,
    height: 12,
    borderRadius: borderRadius.xs,
    backgroundColor: colors.border,
  },
  skeletonDescription: {
    width: '100%',
    height: 40,
    borderRadius: borderRadius.xs,
    backgroundColor: colors.border,
    marginBottom: spacing.md,
  },
  skeletonButton: {
    width: '100%',
    height: 40,
    borderRadius: borderRadius.md,
    backgroundColor: colors.border,
  },
  // Skeleton styles for fishing statistics
  skeletonStatValue: {
    width: 40,
    height: 24,
    borderRadius: borderRadius.xs,
    backgroundColor: colors.border,
    marginBottom: spacing.xxs,
  },
  skeletonStatLabel: {
    width: 50,
    height: 12,
    borderRadius: borderRadius.xs,
    backgroundColor: colors.border,
  },
  // Achievement section styles
  achievementsContainer: {
    marginTop: spacing.md,
    gap: spacing.sm,
  },
  achievementCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  achievementIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  achievementTextContainer: {
    flex: 1,
  },
  achievementName: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 2,
  },
  achievementDescription: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 18,
  },
});
