// styles/reportFormScreenLocalStyles.ts
import { StyleSheet, Platform, Dimensions, StatusBar } from 'react-native';
import { colors, spacing, borderRadius, modals } from './common';

export const localStyles = StyleSheet.create({
  // Label row with info icon
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  // Toast notification styles
  toast: {
    position: "absolute",
    bottom: 40,
    left: 20,
    right: 20,
    backgroundColor: "#28a745",
    borderRadius: borderRadius.md,
    paddingVertical: 14,
    paddingHorizontal: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 15,
    zIndex: 200, // Above scrollView (zIndex: 2) and floating back button (zIndex: 100)
  },
  toastContent: {
    flex: 1,
    marginLeft: 12,
  },
  toastTitle: {
    color: colors.white,
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 2,
  },
  toastSubtitle: {
    color: "rgba(255, 255, 255, 0.9)",
    fontSize: 14,
    fontWeight: "400",
  },
  // Screen container with primary background for header
  screenContainer: {
    flex: 1,
    backgroundColor: colors.primary,
  },

  // Fixed header - sits behind scrolling content
  fixedHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.primary,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 16 : 56,
    paddingBottom: 20,
    paddingHorizontal: 20,
    zIndex: 1,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: borderRadius.md,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextContainer: {
    flex: 1,
    marginLeft: 16,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.white,
  },
  headerSubtitle: {
    fontSize: 13,
    color: colors.white,
    opacity: 0.85,
    marginTop: 2,
  },
  testModeBadge: {
    backgroundColor: '#ff9800',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: borderRadius.md,
    marginRight: 12,
  },
  testModeBadgeText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  headerSpacer: {
    width: 40,
  },

  // FAQ button in header
  faqButton: {
    width: 40,
    height: 40,
    borderRadius: borderRadius.md,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // FAQ Modal styles - uses common modal styles
  faqModalOverlay: modals.overlay,
  faqModalContent: {
    ...modals.content,
    maxHeight: '85%',
  },
  faqModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
  },
  faqModalHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  faqModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  faqScrollView: {
    paddingHorizontal: spacing.md,
  },
  faqItem: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.06)',
  },
  faqQuestion: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.primary,
    marginBottom: 6,
  },
  faqAnswer: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  faqLinkButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
    marginTop: 8,
    marginBottom: spacing.md,
    backgroundColor: colors.primaryLight,
    borderRadius: borderRadius.md,
  },
  faqLinkText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
  },
  faqCloseButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    alignItems: 'center',
  },
  faqCloseButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.white,
  },

  // Floating back button - appears on scroll
  floatingBackButton: {
    position: 'absolute',
    top: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 12 : 52,
    left: 16,
    zIndex: 100,
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  floatingBackTouchable: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Scroll view - slides over fixed header
  scrollView: {
    flex: 1,
    zIndex: 2,
  },
  scrollViewContent: {
    paddingBottom: 40,
  },

  // Header spacer - transparent area showing fixed header behind
  headerSpacerArea: {
    height: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 100 : 130,
    backgroundColor: 'transparent',
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 16 : 56,
    paddingHorizontal: 20,
  },
  spacerButtonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  spacerBackButton: {
    width: 40,
    height: 40,
  },
  spacerFaqButton: {
    width: 40,
    height: 40,
  },

  // Content container - the light card that slides over
  contentContainer: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    paddingTop: 8,
    paddingBottom: 24, // Extra padding for bottom rounded corners
    marginBottom: spacing.lg, // Space below the card to show the rounded corners
    minHeight: Dimensions.get('window').height - 100,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 8,
  },

  // Reporting type styles
  reportingTypeOption: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.md,
    backgroundColor: colors.white,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 12,
  },
  reportingTypeOptionSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.primary,
  },
  reportingTypeText: {
    flex: 1,
    fontSize: 15,
    color: colors.textPrimary,
  },
  peopleCountSection: {
    marginTop: 4,
  },
  // Count picker styles
  countContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  countButton: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.lightGray,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  countInput: {
    flex: 1,
    height: 44,
    marginHorizontal: 12,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "600",
    color: colors.textPrimary,
    backgroundColor: colors.white,
    borderRadius: borderRadius.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  // Optional details styles
  optionalToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    marginBottom: 8,
  },
  optionalToggleText: {
    fontSize: 16,
    fontWeight: "500",
    color: colors.primary,
    marginRight: 6,
  },
  optionalSection: {
    backgroundColor: colors.lightGray,
    borderRadius: borderRadius.sm,
    padding: spacing.sm,
    marginBottom: 8,
  },
  // Multiple lengths styles
  lengthsContainer: {
    marginBottom: 8,
  },
  lengthRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  lengthLabel: {
    width: 32,
    fontSize: 14,
    fontWeight: "600",
    color: colors.darkGray,
  },
  lengthInput: {
    flex: 1,
    height: 40,
    backgroundColor: colors.white,
    borderRadius: borderRadius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    fontSize: 14,
    color: colors.textPrimary,
  },
  // Helper text style
  helperText: {
    fontSize: 12,
    color: colors.darkGray,
    marginBottom: 8,
    fontStyle: "italic",
  },
  // License toggle styles
  licenseToggleContainer: {
    flexDirection: "row",
    gap: 12,
    marginBottom: spacing.md,
  },
  licenseToggleButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.white,
    alignItems: "center",
  },
  licenseToggleButtonActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  licenseToggleText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.darkGray,
  },
  licenseToggleTextActive: {
    color: colors.primary,
  },
  // Name row styles
  nameRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 0,
  },
  nameInput: {
    flex: 1,
    marginBottom: spacing.md,
  },
  // Multi-fish list styles
  fishListContainer: {
    marginTop: 16,
    marginBottom: 8,
  },
  fishListTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.darkGray,
    marginBottom: 8,
  },
  fishChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.lightGray,
    borderRadius: borderRadius.sm,
    marginBottom: 6,
    overflow: "hidden",
  },
  fishChipActive: {
    backgroundColor: colors.primaryLight,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  fishChipContent: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  fishChipText: {
    fontSize: 14,
    color: colors.textPrimary,
  },
  fishChipTextActive: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: "600",
  },
  fishChipRemove: {
    padding: 10,
    paddingLeft: 4,
  },
  addFishButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.primary,
    borderStyle: "dashed",
    borderRadius: borderRadius.sm,
    marginTop: 12,
    backgroundColor: "rgba(11, 84, 139, 0.05)",
  },
  addFishButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.primary,
    marginLeft: 8,
  },
  // Switch toggle styles
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    marginBottom: 8,
  },
  switchLabel: {
    fontSize: 14,
    color: colors.darkGray,
    flex: 1,
    marginRight: 12,
  },
  // Raffle section styles
  raffleSection: {
    backgroundColor: "#fff9e6",
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: spacing.md,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    borderWidth: 1.5,
    borderColor: "#f0c14b",
  },
  raffleSectionEntered: {
    borderColor: colors.success,
    backgroundColor: "#e8f5e9",
  },
  raffleSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  raffleIconContainer: {
    width: 48,
    height: 48,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  raffleIconContainerEntered: {
    backgroundColor: colors.success,
  },
  raffleEnteredMessage: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#e8f5e9",
    padding: spacing.sm,
    borderRadius: borderRadius.sm,
  },
  raffleEnteredText: {
    fontSize: 14,
    color: colors.textPrimary,
    marginLeft: 10,
    flex: 1,
    lineHeight: 20,
  },
  raffleTitleContainer: {
    flex: 1,
  },
  raffleTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  raffleSubtitle: {
    fontSize: 13,
    color: colors.darkGray,
    marginTop: 2,
  },
  raffleDescription: {
    fontSize: 14,
    color: colors.darkGray,
    lineHeight: 20,
    marginBottom: spacing.md,
  },
  raffleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: colors.white,
  },
  raffleButtonSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  raffleButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.primary,
    marginLeft: 8,
  },
  raffleButtonTextSelected: {
    color: colors.white,
  },
  raffleRemoveButton: {
    alignItems: "center",
    paddingVertical: 10,
    marginTop: 8,
  },
  raffleRemoveButtonText: {
    fontSize: 14,
    color: colors.darkGray,
    textDecorationLine: "underline",
  },
  privacyAssurance: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0fdf4",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: borderRadius.sm,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  privacyAssuranceText: {
    flex: 1,
    fontSize: 13,
    color: "#166534",
    lineHeight: 18,
  },
  // CatchFeed photo section (for users already entered in raffle)
  catchFeedPhotoSection: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  catchFeedPhotoLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.textPrimary,
    marginBottom: 4,
  },
  catchFeedPhotoDesc: {
    fontSize: 13,
    color: colors.darkGray,
    marginBottom: 12,
  },
  catchFeedPhotoContainer: {
    alignItems: "center",
  },
  catchFeedPhoto: {
    width: "100%",
    height: 160,
    borderRadius: borderRadius.md,
    backgroundColor: colors.lightGray,
  },
  catchFeedPhotoActions: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 10,
    gap: 16,
  },
  catchFeedPhotoActionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  catchFeedPhotoActionText: {
    fontSize: 14,
    color: colors.primary,
    marginLeft: 6,
  },
  catchFeedAddPhotoButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: colors.primary,
    borderStyle: "dashed",
    paddingVertical: spacing.md,
    gap: 8,
  },
  catchFeedAddPhotoText: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.primary,
  },
  // Raffle modal styles - uses common modal styles
  raffleModalOverlay: modals.overlay,
  raffleModalContent: {
    ...modals.content,
    width: "90%",
    maxHeight: "85%",
  },
  raffleModalScrollContent: {
    padding: spacing.lg,
  },
  raffleModalHeader: {
    alignItems: "center",
    marginBottom: spacing.lg,
  },
  raffleModalIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  raffleModalTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.textPrimary,
    textAlign: "center",
  },
  raffleModalSubtitle: {
    fontSize: 14,
    color: colors.darkGray,
    textAlign: "center",
    marginTop: 4,
  },
  raffleModalText: {
    fontSize: 15,
    color: colors.darkGray,
    marginBottom: spacing.md,
  },
  raffleModalList: {
    marginBottom: spacing.md,
  },
  raffleModalListItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  raffleModalListText: {
    fontSize: 14,
    color: colors.textPrimary,
    marginLeft: 10,
    flex: 1,
    lineHeight: 20,
  },
  raffleModalNote: {
    fontSize: 13,
    color: colors.darkGray,
    fontStyle: "italic",
    marginBottom: spacing.lg,
    textAlign: "center",
  },
  raffleModalButtonsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  raffleModalButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    paddingHorizontal: spacing.md,
    borderRadius: 10,
  },
  raffleModalPrimaryButton: {
    backgroundColor: colors.primary,
  },
  raffleModalSecondaryButton: {
    backgroundColor: colors.lightGray,
  },
  raffleModalPrimaryButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.white,
    marginLeft: 6,
  },
  raffleModalSecondaryButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  raffleModalButtonDisabled: {
    opacity: 0.5,
  },
  raffleModalCloseButton: {
    position: "absolute",
    top: 0,
    right: 0,
    padding: 8,
    zIndex: 1,
  },
  raffleModalSection: {
    marginBottom: spacing.lg,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  raffleModalSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
    marginBottom: 6,
  },
  raffleModalSectionDesc: {
    fontSize: 14,
    color: colors.darkGray,
    marginBottom: 12,
  },
  rafflePhotoContainer: {
    alignItems: "center",
  },
  rafflePhoto: {
    width: "100%",
    height: 180,
    borderRadius: borderRadius.md,
    backgroundColor: colors.lightGray,
  },
  rafflePhotoActions: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 10,
    gap: 16,
  },
  rafflePhotoActionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  rafflePhotoActionText: {
    fontSize: 14,
    color: colors.primary,
    marginLeft: 6,
  },
  raffleTakePhotoButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: borderRadius.md,
    borderWidth: 2,
    borderColor: colors.primary,
    borderStyle: "dashed",
    paddingVertical: 24,
    gap: 8,
  },
  raffleTakePhotoText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.primary,
  },
  raffleInputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textPrimary,
    marginBottom: 6,
    marginTop: 12,
  },
  raffleInput: {
    backgroundColor: colors.lightGray,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 16,
    color: colors.textPrimary,
    borderWidth: 1,
    borderColor: colors.border,
  },
  raffleInputError: {
    borderColor: colors.error || "#FF3B30",
    borderWidth: 1,
  },
  raffleErrorText: {
    color: colors.error || "#FF3B30",
    fontSize: 12,
    marginTop: 4,
  },
  // Photo capture styles
  photoContainer: {
    marginTop: 12,
  },
  catchPhoto: {
    width: "100%",
    height: 250,
    borderRadius: borderRadius.md,
    backgroundColor: colors.lightGray,
  },
  photoActions: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 12,
    gap: 16,
  },
  photoActionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.primaryLight,
  },
  photoRemoveButton: {
    backgroundColor: "#ffebee",
  },
  photoActionText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.primary,
    marginLeft: 6,
  },
  photoSuccessMessage: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#e8f5e9",
    padding: spacing.sm,
    borderRadius: borderRadius.sm,
    marginTop: 12,
  },
  photoSuccessText: {
    fontSize: 14,
    color: colors.success,
    marginLeft: 8,
    flex: 1,
  },
  takePhotoButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.primaryLight,
    borderStyle: "dashed",
    borderRadius: borderRadius.md,
    paddingVertical: 32,
    paddingHorizontal: 24,
    marginTop: 12,
  },
  cameraIconContainer: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  takePhotoTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
    marginBottom: 4,
  },
  takePhotoSubtitle: {
    fontSize: 13,
    color: colors.darkGray,
  },
  // Required field indicator styles
  raffleRequiredNote: {
    fontSize: 13,
    color: colors.primary,
    fontStyle: "italic",
    marginBottom: 12,
  },
  requiredAsterisk: {
    color: "#e53935",
    fontWeight: "600",
  },
  // Inline validation error styles
  inputError: {
    borderColor: "#e53935",
    borderWidth: 1.5,
  },
  errorText: {
    fontSize: 12,
    color: "#e53935",
    marginTop: -8,
    marginBottom: 12,
  },
  // ZIP code input row layout
  zipInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  zipInput: {
    width: 100,
    flex: 0,
  },
  // ZIP code lookup feedback styles
  zipFeedback: {
    flex: 1,
    justifyContent: "center",
    marginLeft: 4,
  },
  zipFeedbackLoading: {
    fontSize: 13,
    color: colors.textSecondary,
    fontStyle: "italic",
  },
  zipFeedbackSuccess: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  zipFeedbackSuccessText: {
    fontSize: 13,
    color: "#28a745",
    fontWeight: "500",
  },
  zipFeedbackWarning: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  zipFeedbackWarningText: {
    fontSize: 13,
    color: "#ff9800",
    fontWeight: "500",
  },
  // Abandonment modal styles - uses common modal styles
  abandonModalOverlay: modals.overlay,
  abandonModalContent: {
    ...modals.content,
    width: "85%",
    alignItems: "center",
  },
  abandonModalIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#fff3e0",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.md,
  },
  abandonModalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.textPrimary,
    marginBottom: 8,
    textAlign: "center",
  },
  abandonModalText: {
    fontSize: 15,
    color: colors.darkGray,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 24,
  },
  abandonModalButtons: {
    flexDirection: "row",
    width: "100%",
    gap: 12,
  },
  abandonModalCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: colors.lightGray,
    alignItems: "center",
  },
  abandonModalCancelText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  abandonModalDiscardButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: "#e53935",
    alignItems: "center",
  },
  abandonModalDiscardText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.white,
  },
  // Checkbox styles for confirmation options
  checkboxRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 4,
    marginTop: 4,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkboxLabel: {
    fontSize: 15,
    color: colors.darkGray,
    flex: 1,
  },
  // Small save button styles
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.white,
    marginTop: 8,
  },
  saveButtonSaved: {
    borderColor: colors.success,
    backgroundColor: "#e8f5e9",
  },
  saveButtonText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.primary,
    marginLeft: 6,
  },
  saveButtonTextSaved: {
    color: colors.success,
  },
  // Date picker modal styles - uses common modal styles
  dateModalOverlay: modals.overlay,
  dateModalContent: {
    ...modals.content,
    width: "90%",
  },
  dateModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  dateModalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  datePickerContainer: {
    width: "100%",
    minHeight: 350,
    backgroundColor: colors.white,
    overflow: "hidden",
  },
  datePickerInline: {
    height: 350,
    width: "100%",
    backgroundColor: colors.white,
  },
  dateModalConfirmButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 16,
  },
  dateModalConfirmText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "600",
  },
  // Selected option styles for dropdowns
  optionItemSelected: {
    backgroundColor: "#e8f4fc",
  },
  optionTextSelected: {
    color: colors.primary,
    fontWeight: "600",
  },
  // Section header with icon styles
  sectionHeaderWithIcon: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  mapIconButton: {
    padding: 10,
    borderRadius: 22,
    backgroundColor: "#e8f4fc",
  },
  // Collapsible contact section styles
  contactSectionToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.primaryLight,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: spacing.md,
    marginTop: 20,
    borderWidth: 1,
    borderColor: "rgba(0, 102, 153, 0.1)",
  },
  contactSectionToggleLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  contactSectionToggleText: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.primary,
  },
  contactSectionContent: {
    backgroundColor: "#fafbfc",
    borderRadius: 10,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    padding: spacing.md,
    marginTop: -2,
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: "rgba(0, 102, 153, 0.1)",
  },
  contactSectionHint: {
    fontSize: 13,
    color: colors.darkGray,
    marginBottom: 4,
    lineHeight: 18,
  },
  phoneDisclaimer: {
    fontSize: 11,
    color: colors.textSecondary,
    marginBottom: 8,
    lineHeight: 15,
    fontStyle: 'italic',
  },
  // Area of Harvest Info Modal styles - uses common modal styles
  areaInfoModalOverlay: modals.overlay,
  areaInfoModalContent: {
    ...modals.content,
    width: "100%",
    maxWidth: 340,
  },
  areaInfoModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  areaInfoModalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.textPrimary,
    marginLeft: 12,
  },
  areaInfoModalText: {
    fontSize: 15,
    color: colors.textSecondary,
    lineHeight: 22,
    marginBottom: 12,
  },
  areaInfoModalButton: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    paddingVertical: 14,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    marginBottom: 12,
  },
  areaInfoModalButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "600",
  },
  areaInfoModalTip: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: colors.primaryLight,
    borderRadius: borderRadius.sm,
    padding: spacing.sm,
    marginBottom: spacing.md,
    gap: 10,
  },
  areaInfoModalTipText: {
    flex: 1,
    fontSize: 14,
    color: colors.primary,
    lineHeight: 20,
  },
  areaInfoModalCloseButton: {
    paddingVertical: 12,
    alignItems: "center",
  },
  areaInfoModalCloseText: {
    color: colors.textSecondary,
    fontSize: 15,
    fontWeight: "500",
  },
});
